apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cj6v8czfh-go 
  janus-idp.io/tekton: cj6v8czfh-go
  backstage.io/kubernetes-id: cj6v8czfh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cj6v8czfh-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml