apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cj6v8czfh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cj6v8czfh-go 
  name: cj6v8czfh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cj6v8czfh-go 
